apiVersion: v1
kind: ConfigMap
metadata:
  name: vermeg-config
  namespace: vermeg-assurance
data:
  # Eureka Configuration
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8761/eureka"
  
  # MongoDB Configuration
  MONGODB_URI: "mongodb://admin:password@mongodb:27017/vermeg_db?authSource=admin"
  MONGODB_DATABASE: "vermeg_db"
  
  # Redis Configuration
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  
  # Keycloak Configuration
  KEYCLOAK_ISSUER_URI: "http://keycloak:8080/realms/vermeg-realm"
  
  # CORS Configuration
  CORS_ALLOWED_ORIGINS: "http://frontend:80"
  
  # Spring Profiles
  SPRING_PROFILES_ACTIVE: "k8s"

  # chatbot-service Configuration
  SPRING_BOOT_BASE_URL: "http://gestionproduit:9093/api"
  GITHUB_MODEL: "gpt-4o-mini"
  GITHUB_URL: "https://models.inference.ai.azure.com"
