package tn.vermeg.gestionproduit.services.chatbot.analysis;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests unitaires pour PromptAnalyzerService
 * Validation de l'extraction des entités depuis les prompts utilisateur
 */
public class PromptAnalyzerServiceTest {

    private PromptAnalyzerService promptAnalyzerService;

    @BeforeEach
    void setUp() {
        promptAnalyzerService = new PromptAnalyzerService();
    }

    // ========== TESTS EXTRACTION TYPEMONTANT ==========

    @Test
    @DisplayName("Doit extraire TARIF_CONVENTIONNE en majuscules")
    void testExtractTypeMontant_TarifConventionne_Majuscules() {
        String prompt = "Créer une garantie avec le type montant TARIF_CONVENTIONNE";
        String result = promptAnalyzerService.extractTypeMontant(prompt);
        assertEquals("TARIF_CONVENTIONNE", result, "Devrait extraire TARIF_CONVENTIONNE en majuscules");
    }

    @Test
    @DisplayName("Doit extraire TARIF_CONVENTIONNE en minuscules")
    void testExtractTypeMontant_TarifConventionne_Minuscules() {
        String prompt = "Créer une garantie avec le type montant tarif conventionne";
        String result = promptAnalyzerService.extractTypeMontant(prompt);
        assertEquals("TARIF_CONVENTIONNE", result, "Devrait extraire TARIF_CONVENTIONNE depuis minuscules");
    }

    @Test
    @DisplayName("Doit extraire FORFAIT")
    void testExtractTypeMontant_Forfait() {
        String prompt = "Créer une garantie avec le type montant forfait";
        String result = promptAnalyzerService.extractTypeMontant(prompt);
        assertEquals("FORFAIT", result, "Devrait extraire FORFAIT");
    }

    @Test
    @DisplayName("Doit extraire FRAIS_REELS")
    void testExtractTypeMontant_FraisReels() {
        String prompt = "Créer une garantie avec le type montant frais reels";
        String result = promptAnalyzerService.extractTypeMontant(prompt);
        assertEquals("FRAIS_REELS", result, "Devrait extraire FRAIS_REELS");
    }

    @Test
    @DisplayName("Doit retourner null si typeMontant non détecté")
    void testExtractTypeMontant_NotDetected() {
        String prompt = "Créer une garantie sans type de montant spécifié";
        String result = promptAnalyzerService.extractTypeMontant(prompt);
        assertNull(result, "Devrait retourner null si non détecté");
    }

    // ========== TESTS EXTRACTION DURÉE MAX CONTRAT ==========

    @Test
    @DisplayName("Doit extraire durée max 36 depuis '12 à 36 mois'")
    void testExtractDureeMaxContrat_Range() {
        String prompt = "durée de contrat de 12 à 36 mois";
        Integer result = promptAnalyzerService.extractDureeMaxContrat(prompt);
        assertEquals(36, result, "Devrait extraire 36 comme durée max");
    }

    @Test
    @DisplayName("Doit extraire durée max depuis 'entre X et Y mois'")
    void testExtractDureeMaxContrat_Between() {
        String prompt = "durée de contrat entre 12 et 48 mois";
        Integer result = promptAnalyzerService.extractDureeMaxContrat(prompt);
        assertEquals(48, result, "Devrait extraire 48 comme durée max");
    }

    @Test
    @DisplayName("Doit extraire durée max depuis pattern standard")
    void testExtractDureeMaxContrat_StandardPattern() {
        String prompt = "durée maximum contrat de 60 mois";
        Integer result = promptAnalyzerService.extractDureeMaxContrat(prompt);
        assertEquals(60, result, "Devrait extraire 60 comme durée max");
    }

    @Test
    @DisplayName("Doit retourner null si durée max non détectée")
    void testExtractDureeMaxContrat_NotDetected() {
        String prompt = "Créer une garantie sans durée spécifiée";
        Integer result = promptAnalyzerService.extractDureeMaxContrat(prompt);
        assertNull(result, "Devrait retourner null si non détecté");
    }

    // ========== TESTS EXTRACTION DESCRIPTION ==========

    @Test
    @DisplayName("Doit extraire description explicite")
    void testExtractDescription_Explicit() {
        String prompt = "Créer une garantie avec la description: Couverture complète des soins cardiaques pour les patients";
        String result = promptAnalyzerService.extractDescription(prompt);
        assertNotNull(result, "Devrait extraire la description");
        assertTrue(result.contains("soins cardiaques"), "La description devrait contenir le texte extrait");
    }

    @Test
    @DisplayName("Doit générer description automatique si non trouvée")
    void testExtractDescription_AutoGenerated() {
        String prompt = "Créer une garantie nommée Cardiologie Premium avec le domaine CARDIOLOGIE";
        String result = promptAnalyzerService.extractDescription(prompt);
        assertNotNull(result, "Devrait générer une description automatique");
        assertTrue(result.contains("Cardiologie Premium"), "La description devrait contenir le nom");
        assertTrue(result.contains("CARDIOLOGIE"), "La description devrait contenir le domaine");
    }

    @Test
    @DisplayName("Doit retourner null si impossible de générer description")
    void testExtractDescription_NotPossible() {
        String prompt = "Créer une garantie sans nom ni domaine";
        String result = promptAnalyzerService.extractDescription(prompt);
        assertNull(result, "Devrait retourner null si impossible de générer");
    }

    // ========== TESTS EXTRACTION COÛT MOYEN PAR SINISTRE ==========

    @Test
    @DisplayName("Doit extraire coût moyen par sinistre")
    void testExtractCoutMoyenParSinistre() {
        String prompt = "coût moyen par sinistre de 1500 euros";
        Double result = promptAnalyzerService.extractCoutMoyenParSinistre(prompt);
        assertEquals(1500.0, result, "Devrait extraire 1500 comme coût moyen");
    }

    @Test
    @DisplayName("Doit retourner null si coût moyen non détecté")
    void testExtractCoutMoyenParSinistre_NotDetected() {
        String prompt = "Créer une garantie sans coût moyen spécifié";
        Double result = promptAnalyzerService.extractCoutMoyenParSinistre(prompt);
        assertNull(result, "Devrait retourner null si non détecté");
    }

    // ========== TESTS EXTRACTION RÉSILIABLE ANNUELLEMENT ==========

    @Test
    @DisplayName("Doit détecter résiliable annuellement")
    void testExtractResiliableAnnuellement_True() {
        String prompt = "garantie résiliable annuellement";
        Boolean result = promptAnalyzerService.extractResiliableAnnuellement(prompt);
        assertTrue(result, "Devrait détecter résiliable annuellement comme true");
    }

    @Test
    @DisplayName("Doit retourner null si non spécifié")
    void testExtractResiliableAnnuellement_NotSpecified() {
        String prompt = "Créer une garantie sans mention de résiliation";
        Boolean result = promptAnalyzerService.extractResiliableAnnuellement(prompt);
        assertNull(result, "Devrait retourner null si non spécifié");
    }

    // ========== TESTS SCÉNARIO COMPLET ==========

    @Test
    @DisplayName("Scénario complet: Prompt avec toutes les informations")
    void testScenarioComplet_ToutesInformations() {
        String prompt = "Créer une garantie nommée Cardiologie Premium avec le domaine CARDIOLOGIE et le type montant TARIF_CONVENTIONNE et un taux de remboursement de 80 pourcent et un plafond annuel de 30000 et un plafond mensuel de 2500 et un plafond par acte de 1500 et une franchise de 50 et un coût moyen par sinistre de 1500 et une durée de contrat de 12 à 36 mois et résiliable annuellement et statut ACTIF";

        // Extraction nom
        String nom = promptAnalyzerService.extractNomGarantie(prompt);
        assertEquals("Cardiologie Premium", nom, "Nom extrait correctement");

        // Extraction domaine
        String domaine = promptAnalyzerService.extractDomaineMedical(prompt);
        assertEquals("CARDIOLOGIE", domaine, "Domaine extrait correctement");

        // Extraction typeMontant
        String typeMontant = promptAnalyzerService.extractTypeMontant(prompt);
        assertEquals("TARIF_CONVENTIONNE", typeMontant, "TypeMontant extrait correctement");

        // Extraction taux
        Double taux = promptAnalyzerService.extractTauxRemboursement(prompt);
        assertEquals(0.8, taux, "Taux extrait correctement");

        // Extraction durée max
        Integer dureeMax = promptAnalyzerService.extractDureeMaxContrat(prompt);
        assertEquals(36, dureeMax, "Durée max extraite correctement");

        // Extraction coût moyen
        Double coutMoyen = promptAnalyzerService.extractCoutMoyenParSinistre(prompt);
        assertEquals(1500.0, coutMoyen, "Coût moyen extrait correctement");

        // Extraction résiliable
        Boolean resiliable = promptAnalyzerService.extractResiliableAnnuellement(prompt);
        assertTrue(resiliable, "Résiliable extrait correctement");

        // Extraction description
        String description = promptAnalyzerService.extractDescription(prompt);
        assertNotNull(description, "Description générée automatiquement");
    }

    @Test
    @DisplayName("Scénario avec valeurs manquantes")
    void testScenarioValeursManquantes() {
        String prompt = "Créer une garantie nommée Test";

        String typeMontant = promptAnalyzerService.extractTypeMontant(prompt);
        assertNull(typeMontant, "TypeMontant devrait être null");

        Integer dureeMax = promptAnalyzerService.extractDureeMaxContrat(prompt);
        assertNull(dureeMax, "Durée max devrait être null");

        Double coutMoyen = promptAnalyzerService.extractCoutMoyenParSinistre(prompt);
        assertNull(coutMoyen, "Coût moyen devrait être null");
    }
}
